export const predefinedScenarios = {
  person: {
    helse: [
      "pasient med kronisk sykdom",
      "eldre med demens",
      "person med psykiske lidelser",
      "pasient med rusproblemer",
      "barn med funksjonshemming",
      "pasient med sjelden diagnose",
      "person med smerteproblematikk",
      "pasient med multimorbiditet",
      "person med kognitiv svikt",
      "pasient i palliativ fase",
      "person med angst og depresjon",
      "pasient med diabetes",
    ],
    barnevern: [
      "barn med atferdsvansker",
      "ungdom med skolevegring",
      "barn i omsorgssviktsituasjon",
      "barn med tilknytningsvansker",
      "ungdom med rusproblemer",
      "barn med psykiske utfordringer",
      "barn i konfliktfylt skilsmisse",
      "ungdom med kriminell atferd",
      "barn med flyktningbakgrunn",
      "barn med foreldre med psykisk sykdom",
      "barn med foreldre med rusproblemer",
      "ungdom med selvskading",
    ],
    politi: [
      "person med psykisk lidelse",
      "ungdom i risikosone",
      "person med rusproblemer",
      "offer for vold i nære relasjoner",
      "person med kriminell bakgrunn",
      "vitne til alvorlig hendelse",
      "person med aggressiv atferd",
      "person i akutt krise",
      "person med selvmordsrisiko",
      "person med minoritetsbakgrunn",
      "person med språkbarrierer",
      "person med kognitive utfordringer",
    ],
    forsvaret: [
      "soldat med stressreaksjoner",
      "veteran med PTSD",
      "befal med lederutfordringer",
      "personell i internasjonal tjeneste",
      "rekrutt med tilpasningsvansker",
      "offiser med etiske dilemmaer",
      "soldat med fysiske skader",
      "personell med sikkerhetsvurderinger",
      "veteran med reintegreringsutfordringer",
      "befal med familieutfordringer",
      "personell med lojalitetskonflikt",
      "soldat med motivasjonsutfordringer",
    ],
    nav: [
      "bruker med langvarig sykefravær",
      "person med nedsatt arbeidsevne",
      "ungdom uten fullført utdanning",
      "innvandrer med språkutfordringer",
      "person med gjeldsproblemer",
      "langtidsledig med kompetansegap",
      "enslig forsørger med økonomiske utfordringer",
      "person med rushistorikk",
      "bruker med psykiske helseutfordringer",
      "person med funksjonsnedsettelse",
      "eldre arbeidssøker",
      "person i yrkesrettet attføring",
    ],
  },
  challenge: {
    helse: [
      "møter ressursmangel i tjenesten",
      "opplever etiske dilemmaer",
      "mangler tverrfaglig samarbeid",
      "har kommunikasjonsutfordringer",
      "møter kulturelle barrierer",
      "opplever systemsvikt",
      "mangler kompetanse på området",
      "har utfordringer med pårørende",
      "møter prioriteringsdilemmaer",
      "opplever tidspress",
      "har utfordringer med samtykkekompetanse",
      "møter teknologiske barrierer",
    ],
    barnevern: [
      "opplever samarbeidsvansker med foreldre",
      "møter kulturelle utfordringer",
      "har ressursmangel i tjenesten",
      "opplever etiske dilemmaer",
      "mangler tverrfaglig samarbeid",
      "har utfordringer med medvirkning",
      "møter motstand fra familien",
      "opplever lojalitetskonflikt",
      "har utfordringer med dokumentasjon",
      "møter systemiske barrierer",
      "opplever høyt arbeidspress",
      "har utfordringer med fosterhjemsplassering",
    ],
    politi: [
      "står i etiske dilemmaer",
      "møter ressursbegrensninger",
      "opplever krysspress",
      "har utfordringer med samarbeid",
      "møter kulturelle barrierer",
      "opplever mediehåndtering",
      "har utfordringer med maktbruk",
      "møter komplekse juridiske spørsmål",
      "opplever tidspress i akuttsituasjoner",
      "har utfordringer med informasjonsdeling",
      "møter teknologiske begrensninger",
      "opplever personlige sikkerhetsutfordringer",
    ],
    forsvaret: [
      "står i etiske dilemmaer",
      "møter interkulturelle utfordringer",
      "opplever kommandolinjeproblemer",
      "har utfordringer med sivil-militært samarbeid",
      "møter ressursbegrensninger",
      "opplever sikkerhetsdilemmaer",
      "har utfordringer med stressmestring",
      "møter folkerettslige spørsmål",
      "opplever lojalitetskonflikter",
      "har utfordringer med mediehåndtering",
      "møter teknologiske begrensninger",
      "opplever personellmangel",
    ],
    nav: [
      "møter komplekse regelverk",
      "opplever systemiske barrierer",
      "har utfordringer med brukermedvirkning",
      "møter ressursbegrensninger",
      "opplever etiske dilemmaer",
      "har utfordringer med tverrfaglig samarbeid",
      "møter digitale barrierer",
      "opplever målkonflikter",
      "har utfordringer med arbeidsmarkedstiltak",
      "møter kulturelle utfordringer",
      "opplever høyt arbeidspress",
      "har utfordringer med dokumentasjonskrav",
    ],
  },
  outcome: {
    helse: [
      "får ikke nødvendig helsehjelp",
      "opplever forverret helsetilstand",
      "mister tillit til helsevesenet",
      "får mangelfull oppfølging",
      "opplever unødvendig lidelse",
      "får feilbehandling",
      "mister autonomi",
      "opplever brudd på taushetsplikt",
      "får økonomiske konsekvenser",
      "opplever diskriminering",
      "mister sosialt nettverk",
      "får redusert livskvalitet",
    ],
    barnevern: [
      "opplever ustabilitet i omsorgssituasjonen",
      "får mangelfull oppfølging",
      "mister tillit til barnevernet",
      "opplever brudd i relasjoner",
      "får utviklingsforstyrrelser",
      "mister medvirkningsmuligheter",
      "opplever traumatisering",
      "får mangelfull skolegang",
      "mister sosialt nettverk",
      "opplever identitetsutfordringer",
      "får psykiske helseproblemer",
      "opplever diskriminering",
    ],
    politi: [
      "mister tillit til politiet",
      "opplever rettssikkerhetsbrudd",
      "får mangelfull beskyttelse",
      "opplever sekundærtraumatisering",
      "får økonomiske konsekvenser",
      "mister sosialt nettverk",
      "opplever stigmatisering",
      "får psykiske belastninger",
      "mister personlig frihet",
      "opplever diskriminering",
      "får mangelfull oppfølging",
      "opplever retraumatisering",
    ],
    forsvaret: [
      "opplever moralsk stress",
      "får psykiske helseproblemer",
      "mister karrieremuligheter",
      "opplever sosial isolasjon",
      "får fysiske skader",
      "mister tillit til ledelsen",
      "opplever identitetskrise",
      "får økonomiske konsekvenser",
      "mister sosialt nettverk",
      "opplever stigmatisering",
      "får reintegreringsutfordringer",
      "opplever familieutfordringer",
    ],
    nav: [
      "havner i økonomisk krise",
      "opplever langvarig arbeidsledighet",
      "mister bolig",
      "får redusert livskvalitet",
      "opplever sosial isolasjon",
      "mister tillit til velferdssystemet",
      "får psykiske helseproblemer",
      "opplever stigmatisering",
      "mister kompetanseutvikling",
      "får reduserte fremtidsmuligheter",
      "opplever fattigdomsproblematikk",
      "mister motivasjon",
    ],
  },
}

export function getRandomScenario(
  category: keyof typeof predefinedScenarios,
  domain: string,
  currentDescription?: string,
): string {
  const domainScenarios =
    predefinedScenarios[category][domain as keyof (typeof predefinedScenarios)[typeof category]] ||
    predefinedScenarios[category]["helse"] // Fallback to helse if domain not found

  const filteredScenarios = currentDescription
    ? domainScenarios.filter((s) => s !== currentDescription)
    : domainScenarios

  const randomIndex = Math.floor(Math.random() * filteredScenarios.length)
  return filteredScenarios[randomIndex]
}

